[package]
name = "lang3"
version = "0.1.0"
authors = ["Nikola Tasic <ntasic7@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
phf = { version = "0.11.1", features = ["macros"] }